/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveysSurveyIdRouteImport } from './routes/surveys.$surveyId'
import { Route as SurveySurveyIdRouteImport } from './routes/survey.$surveyId'
import { Route as SurveysSurveyIdResponsesRouteImport } from './routes/surveys.$surveyId.responses'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysSurveyIdRoute = SurveysSurveyIdRouteImport.update({
  id: '/surveys/$surveyId',
  path: '/surveys/$surveyId',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveySurveyIdRoute = SurveySurveyIdRouteImport.update({
  id: '/survey/$surveyId',
  path: '/survey/$surveyId',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysSurveyIdResponsesRoute =
  SurveysSurveyIdResponsesRouteImport.update({
    id: '/responses',
    path: '/responses',
    getParentRoute: () => SurveysSurveyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/survey/$surveyId': typeof SurveySurveyIdRoute
  '/surveys/$surveyId': typeof SurveysSurveyIdRouteWithChildren
  '/surveys/$surveyId/responses': typeof SurveysSurveyIdResponsesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/survey/$surveyId': typeof SurveySurveyIdRoute
  '/surveys/$surveyId': typeof SurveysSurveyIdRouteWithChildren
  '/surveys/$surveyId/responses': typeof SurveysSurveyIdResponsesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/survey/$surveyId': typeof SurveySurveyIdRoute
  '/surveys/$surveyId': typeof SurveysSurveyIdRouteWithChildren
  '/surveys/$surveyId/responses': typeof SurveysSurveyIdResponsesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/survey/$surveyId'
    | '/surveys/$surveyId'
    | '/surveys/$surveyId/responses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/survey/$surveyId'
    | '/surveys/$surveyId'
    | '/surveys/$surveyId/responses'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/survey/$surveyId'
    | '/surveys/$surveyId'
    | '/surveys/$surveyId/responses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SurveySurveyIdRoute: typeof SurveySurveyIdRoute
  SurveysSurveyIdRoute: typeof SurveysSurveyIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/$surveyId': {
      id: '/surveys/$surveyId'
      path: '/surveys/$surveyId'
      fullPath: '/surveys/$surveyId'
      preLoaderRoute: typeof SurveysSurveyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/$surveyId': {
      id: '/survey/$surveyId'
      path: '/survey/$surveyId'
      fullPath: '/survey/$surveyId'
      preLoaderRoute: typeof SurveySurveyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/$surveyId/responses': {
      id: '/surveys/$surveyId/responses'
      path: '/responses'
      fullPath: '/surveys/$surveyId/responses'
      preLoaderRoute: typeof SurveysSurveyIdResponsesRouteImport
      parentRoute: typeof SurveysSurveyIdRoute
    }
  }
}

interface SurveysSurveyIdRouteChildren {
  SurveysSurveyIdResponsesRoute: typeof SurveysSurveyIdResponsesRoute
}

const SurveysSurveyIdRouteChildren: SurveysSurveyIdRouteChildren = {
  SurveysSurveyIdResponsesRoute: SurveysSurveyIdResponsesRoute,
}

const SurveysSurveyIdRouteWithChildren = SurveysSurveyIdRoute._addFileChildren(
  SurveysSurveyIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SurveySurveyIdRoute: SurveySurveyIdRoute,
  SurveysSurveyIdRoute: SurveysSurveyIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
